server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
      server:
        webflux:
          default-filters:
            - TokenRelay
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes: 
            - id: msvc-product
              uri: lb://msvc-product
              predicates:
                - Path=/api/products/**
            - id: msvc-order
              uri: lb://msvc-order
              predicates:
                - Path=/api/orders/**
  
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:api-gateway-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid, profile, email, roles
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:8080/login/oauth2/code/keycloak}
        provider:
          keycloak:
            issuer-uri: http://localhost:7080/realms/order-system


  output:
    ansi:
      enabled: ALWAYS
    
  
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG