spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/order-system
  config:
    activate:
      on-profile: dev

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      productCB:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers,tracing,prometheus" # promethes proximamente
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true

  # Configuración de Tracing (Micrometer + Zipkin)
  tracing:
    sampling:
      probability: 1.0 # 1.0 significa que envía el 100% de las trazas 
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    io.github.resilience4j: DEBUG
    # Importante para ver si las trazas se están enviando
    org.springframework.web.client.RestTemplate: DEBUG