spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/order-system

eureka:
  client:
    enabled: true       
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true