server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_system?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/order-system

eureka:
  client:
    enabled: true        # Asegúrate de que no esté en false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
